name: Docker

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t iab-reader:latest .

    - name: Test Docker image
      run: docker run -v "$(pwd)/tests/assets:/assets" --rm iab-reader:latest /assets/silence.iab

